### ISSUE TITLE
Unknown: java.lang.IllegalArgumentException: Comparison method violates its general contract! when browsing.

### ISSUE THREAD

**Issue by DutchComputerKid** [tesshucom/jpsonic#1986] opened 2023-01-05 17:57 UTC
## Problem description

Now this is a wierd one, mostly when trying to log in or out this pops up, but from what I remember sometimes with browsing too.
This has been popping up for a while now but since I have not found anything concrete about how to trigger it, I just saved a couple error 'logs'.
[error3.txt](https://github.com/tesshucom/jpsonic/files/10354492/error3.txt)
[error2.txt](https://github.com/tesshucom/jpsonic/files/10354493/error2.txt)
[error.txt](https://github.com/tesshucom/jpsonic/files/10354494/error.txt)

### Steps to reproduce

I'm not certain, like I said it mostly happens when logging in from a normal user to admin user, since as I put in issue #1985, starting JPSonic to do a library scan requires logging into the admin user for now.

## System information

 * **Jpsonic version**: *  Jpsonic 111.5.13 – 2022-12-25*
 * **Operating system**: *Debian 11.6
 * **Java version**: *openjdk 17.0.4 2022-07-19*
 * **Proxy server**: None
 * **Client**: *Firefox, Edge, Chrome*
 * **Language**: *English (United States)*
 * **Tomcat/standalone**: *Docker latest*

**Comment by tesshucom** [comment] 2023-01-05 18:26
Thank you for your report. I saw it for the first time. But it's the kind of problem that should be fixed. It may take some time to reproduce, but it will be addressed.

**Comment by tesshucom** [comment] 2023-01-12 15:03
Hi.

We are investigating this issue. From the error message reported, the cause is relatively clear. 

<details>
<summary>the cause</summary>

Sort logic was scattered in Subsonic and Airsonic. Moreover, the content differs depending on the implementation location. In Jpsonic, the sorting logic is managed centrally in one place. But ...

Part of [the Comparator](https://github.com/tesshucom/jpsonic/blob/master/jpsonic-main/src/main/java/com/tesshu/jpsonic/domain/JpMediaFileComparator.java)  has a problem. Sorting logic has two main points of view: Asymmetry and Transitive. Maybe ... the Transitive isn't perfect now.

#### Asymmetry

> Implementers must ensure that signum(compare(x, y)) == -signum(compare(y, x)) for all x and y.

#### Transitive

> Implementers must also ensure that the relation is transitive: ((compare(x, y)>0) && (compare(y, z)>0)) means that compare(x, z)> means 0.

... I'm assuming that, but it's quite difficult to reproduce, so it's going to take a while.


</details>

It looks like a bug located in an edge case.  I will fix this, even if it takes time. However, I cannot guarantee when it will be, so I will propose an alternative plan.

You can suppress the error with the following arguments.

> -Djava.util.Arrays.useLegacyMergeSort=true

The class TimSort in the error message is one of the JDK mechanisms for speeding up sorting. It's fast, but requires a complete sorting logic implementation. There was some confusion expected when this mechanism was introduced, so there are options to suppress it.

If you can avoid it with the above option, please wait for a while until the root solution is resolved. . .

**Comment by tesshucom** [comment] 2023-01-17 02:35
@DutchComputerKid

I am currently thinking of doing the following.

 - Better fix it. but not urgent.
   - It's probably an edge case. 
   - Workarounds exist and are **not blocker** for other feature development. Also, the workaround is unlikely to cause fatal side effects. It's unlikely to be actively addressed until at least the release of v111.6.0.
   - The sorting feature is transitional. It's now better than Subsonic and Airsonic, but it will get better.
     - There may be a possibility that it will not be reproduced due to another fix planned in the future. (To be replaced by another. They were originally planned.)
     - The feature relevant to this issue is the index, but it is expected to be fixed at least. #1879
 - I won't fix it until it's reproducible.
   - The logic in question is limited. They will not be fixed without additional test cases. But, a unit test that intentionally triggers a "general contract violation" is actually quite difficult. Even if understand how it works.
   - I fully understand where the logic in question is being used. Future improvements will make them less and less. Because they will be replaced by different, more better sorting logic and caching.

If you would like to see more accurate progress on this Issues, it would be helpful if you could provide your data.

**Comment by DutchComputerKid** [comment] 2023-01-20 17:08
Excuse the late response, some hardware fixes and docker shenanigans were needed, but  `-Djava.util.Arrays.useLegacyMergeSort=true` seems to have worked.

So in that case, the main underlying problem can indeed be dealt be with later. 
Browsing will not need a full container restart every time the error pops up now.

**Comment by tesshucom** [comment] 2023-01-22 16:51
Now that the workaround works, this issue will be closed once. This is because if you proceed with other improvements, it will be possible to further narrow down the cause.
(Will be closed, but may be referenced by related issues such as #1879.) 

Similar reports by other users are also welcome. If you would like to dig deeper into this issue, please provide reproducible data if possible. We probably want the data in the media_file table.

**Comment by tesshucom** [comment] 2023-01-31 17:55
I was able to reproduce it by chance! Will be fixed in hotfix.

**Comment by tesshucom** [comment] 2023-02-01 18:02
The fix was made in v111.5.17. If upgrading, remove ``-Djava.util.Arrays.useLegacyMergeSort=true``.

**Closed by tesshucom** 2023-02-01 18:02 UTC
Labels: type: bug, in: sort (provisional), type: hotfix
